import type { Metadata } from 'next'
import { GoogleTagManager } from '@next/third-parties/google'

import { ScrollProvider } from '@/lib/contexts/scroll'
import { cn, isDev } from '@/lib/utils'
import Footer from '@/components/footer'
import Navbar from '@/components/navbar'
import WhatsApp from '@/components/whatsapp'

import { roboto } from './fonts'

import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html
      lang='es'
      className={cn(roboto.variable, 'h-full w-full bg-white antialiased')}
    >
      <body className='relative min-h-full w-screen scroll-smooth'>
        {!isDev && <GoogleTagManager gtmId={process.env.NEXT_PUBLIC_GTM_ID} />}
        <ScrollProvider>
          <div className='size-full font-sans text-base font-normal text-slate-500'>
            <div className='size-full'>
              <Navbar />
              {children}

              <Footer />
            </div>
          </div>
        </ScrollProvider>
        <WhatsApp />
      </body>
    </html>
  )
}
